version: '3.9'
services:
  hub:
    build:
      context: .
    ports:
      - "80:80"
    depends_on:
      hubdb:
        condition: service_started
    links:
      - hubdb
    volumes:
      - ./simplecamera:/var/www/html/moodle/blocks/simplecamera
      - ./faceid:/var/www/html/moodle/auth/faceid
      - ./sentimentsdata:/var/www/html/moodle/blocks/sentimentsdata
      - ./setup:/var/www/html/moodle/setup
      - moodle:/var/www/html/moodle
      - moodle-data:/var/www/moodledata
    env_file:
      - .env
  hubdb:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=moodle
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
  moodle:
  moodle-data: